### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by FiftyFour7250** [itsjustaplant/spofly#4]
I wanted to check it out, but it doesn't work. Authorization error(

![Снимок](https://user-images.githubusercontent.com/78786088/110282211-23d4ec00-7fef-11eb-83c5-59babea56cbb.JPG)

**Comment by itsjustaplant** [comment]
Hey, thanks for opening an issue. I am currently reviewing the logs to figure out what the problem is.

**Comment by itsjustaplant** [comment]
I fixed the issue and updated the app.

**Comment by FiftyFour7250** [comment]
Still doesn't work for me :c

Even after deleting cookies

Are you sure that you uploaded the new update?

**Comment by itsjustaplant** [comment]
As i understand, it happens when user logins without playing any song on Spotify. I'm currently trying my best to solve it. Would you please try again with playing a song on Spotify?
Stay with music.
<img width="1440" alt="Screen Shot 2021-03-09 at 01 07 12" src="https://user-images.githubusercontent.com/42607830/110388231-cf278480-8073-11eb-91ef-65a47c475a39.png">

**Comment by FiftyFour7250** [comment]
Yea, if song is playing - it works fine.

**Comment by itsjustaplant** [comment]
I added a simple good looking 404 page. I'm going to improve the UI/UX quality soon. Thank you for interest in spofly. I also developed mac and generic app of spofly.
Stay with music.
